### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by Nanzhuojun** [Anwar8/OSPCR-MP#1]
Hi,    @Anwar,

I try to use your OpenSEES for multiply analysis of I beam 2D heat transfer.
The only variable in my .tcl is section location (-SectionLoc $SecLoc). 

The analysis can run, but the Report.txt can not report the error analysis.
I try to test an error definition of $SecLoc, for example, 'potato'. The result in the Report.txt is still 'OK'.

Could you please recheck it?
And my .tcl and .dat have been attached.

Many thanks.

[TestIssue_NAN.zip](https://github.com/Anwar8/OSPCR-MP/files/6047842/TestIssue_NAN.zip)

**Comment by Anwar8** [comment]
Dear Nan,

Thank you for reporting this issue and for sharing your files. 
Would you kindly try this attached updated executable and let me know if everything is okay now
[OSPCR-MP.zip](https://github.com/Anwar8/OSPCR-MP/files/6048483/OSPCR-MP.zip)

?

Best,
Anwar

**Comment by Nanzhuojun** [comment]
> Dear Nan,
> 
> Thank you for reporting this issue and for sharing your files.
> Would you kindly try this attached updated executable and let me know if everything is okay now
> [OSPCR-MP.zip](https://github.com/Anwar8/OSPCR-MP/files/6048483/OSPCR-MP.zip)
> 
> ?
> 
> Best,
> Anwar

**Comment by Nanzhuojun** [comment]
Dear Anwar,

The issue has been solved. 
After updating the OSPCR-MP.exe on my laptop, the Report.txt summarized the correct report for all cases.

![image](https://user-images.githubusercontent.com/52700864/109637108-4eeeb400-7b87-11eb-9321-f55601e4586d.png)

Thank you again for your help.
